In [7]:
# Softmax 예제
import numpy as np

In [2]:
a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a) # 지수 함수
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [4]:
sum_exp_a = np.sum(exp_a) # 지수 함수의 합
"""
분류에서 사용하는 소프트맥스 함수의 식:
y_k = (exp(a_k))/sum of exp(a_i)
(i: 1~n)
"""
print(sum_exp_a)

74.1221542101633


In [5]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [8]:
# Softmax 함수의 정의
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [11]:
# overflow 방지를 위한 Softmax 함수의 변형
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) # overflow 대책
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [15]:
# Softmax 함수의 특징
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)
np.sum(y)

# Softmax 함수의 출력은 0 ~ 1.0 사이 실수, 합은 1 >>> 확률로 해석 가능

[0.01821127 0.24519181 0.73659691]


1.0